version: "3.7"
services:
  influxdb:
    container_name: influxdb-dev
    image: influxdb:latest
    volumes: 
      - C:\dev\influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=A123456!
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=A123456!
    ports:
      - 8086:8086
    networks:
      - influxdb
  chronograf:
    container_name: chronograf-dev
    image: chronograf:latest
    environment:
      - INFLUXDB_URL=http://influxdb:8086
    ports:
      - 8888:8888
    networks:
      - influxdb
networks:
  influxdb:
    name: influxdb